
/**
* DVRMS/DVRMSHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DVRMS.idl
* vendredi 27 f�vrier 2026 18 h 00 EST
*/

abstract public class DVRMSHelper
{
  private static String  _id = "IDL:DVRMS/DVRMS:1.0";

  public static void insert (org.omg.CORBA.Any a, DVRMS that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DVRMS extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (DVRMSHelper.id (), "DVRMS");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DVRMS read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DVRMSStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DVRMS value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static DVRMS narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DVRMS)
      return (DVRMS)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _DVRMSStub stub = new _DVRMSStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static DVRMS unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DVRMS)
      return (DVRMS)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      _DVRMSStub stub = new _DVRMSStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
