package com.dvrms.replica2;
/**
* DVRMS/DVRMSPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DVRMS.idl
* vendredi 27 f�vrier 2026 18 h 00 EST
*/

public abstract class DVRMSPOA extends org.omg.PortableServer.Servant
 implements DVRMSOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addVehicle", new java.lang.Integer (0));
    _methods.put ("removeVehicle", new java.lang.Integer (1));
    _methods.put ("listAvailableVehicle", new java.lang.Integer (2));
    _methods.put ("reserveVehicle", new java.lang.Integer (3));
    _methods.put ("cancelReservation", new java.lang.Integer (4));
    _methods.put ("updateReservation", new java.lang.Integer (5));
    _methods.put ("findVehicle", new java.lang.Integer (6));
    _methods.put ("displayCurrentBudget", new java.lang.Integer (7));
    _methods.put ("displayReservations", new java.lang.Integer (8));
    _methods.put ("displayReservationsLocal", new java.lang.Integer (9));
    _methods.put ("retryCustomerWaitlistsLocal", new java.lang.Integer (10));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // ================= MANAGER OPERATIONS =================
       case 0:  // DVRMS/DVRMS/addVehicle
       {
         String managerID = in.read_string ();
         String vehicleNumber = in.read_string ();
         String vehicleType = in.read_string ();
         String vehicleID = in.read_string ();
         double price = in.read_double ();
         String $result = null;
         $result = this.addVehicle (managerID, vehicleNumber, vehicleType, vehicleID, price);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // DVRMS/DVRMS/removeVehicle
       {
         String managerID = in.read_string ();
         String vehicleID = in.read_string ();
         String $result = null;
         $result = this.removeVehicle (managerID, vehicleID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // DVRMS/DVRMS/listAvailableVehicle
       {
         String managerID = in.read_string ();
         String $result = null;
         $result = this.listAvailableVehicle (managerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }


  // ================= CUSTOMER OPERATIONS =================
       case 3:  // DVRMS/DVRMS/reserveVehicle
       {
         String customerID = in.read_string ();
         String vehicleID = in.read_string ();
         String startDate = in.read_string ();
         String endDate = in.read_string ();
         String $result = null;
         $result = this.reserveVehicle (customerID, vehicleID, startDate, endDate);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // DVRMS/DVRMS/cancelReservation
       {
         String customerID = in.read_string ();
         String vehicleID = in.read_string ();
         String $result = null;
         $result = this.cancelReservation (customerID, vehicleID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // DVRMS/DVRMS/updateReservation
       {
         String customerID = in.read_string ();
         String vehicleID = in.read_string ();
         String newStartDate = in.read_string ();
         String newEndDate = in.read_string ();
         String $result = null;
         $result = this.updateReservation (customerID, vehicleID, newStartDate, newEndDate);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // DVRMS/DVRMS/findVehicle
       {
         String customerID = in.read_string ();
         String vehicleType = in.read_string ();
         String $result = null;
         $result = this.findVehicle (customerID, vehicleType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // DVRMS/DVRMS/displayCurrentBudget
       {
         String customerID = in.read_string ();
         String $result = null;
         $result = this.displayCurrentBudget (customerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 8:  // DVRMS/DVRMS/displayReservations
       {
         String customerID = in.read_string ();
         String $result = null;
         $result = this.displayReservations (customerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 9:  // DVRMS/DVRMS/displayReservationsLocal
       {
         String customerID = in.read_string ();
         String $result = null;
         $result = this.displayReservationsLocal (customerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 10:  // DVRMS/DVRMS/retryCustomerWaitlistsLocal
       {
         String customerID = in.read_string ();
         String $result = null;
         $result = this.retryCustomerWaitlistsLocal (customerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:DVRMS/DVRMS:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public DVRMS _this() 
  {
    return DVRMSHelper.narrow(
    super._this_object());
  }

  public DVRMS _this(org.omg.CORBA.ORB orb) 
  {
    return DVRMSHelper.narrow(
    super._this_object(orb));
  }


} // class DVRMSPOA
