
/**
* DVRMS/DVRMS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DVRMS.idl
* vendredi 27 f�vrier 2026 18 h 00 EST
*/

public interface DVRMS extends DVRMSOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{

} // interface DVRMS
