
/**
* DVRMS/DVRMSHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DVRMS.idl
* vendredi 27 f�vrier 2026 18 h 00 EST
*/

public final class DVRMSHolder implements org.omg.CORBA.portable.Streamable
{
  public DVRMS value = null;

  public DVRMSHolder ()
  {
  }

  public DVRMSHolder (DVRMS initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DVRMSHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DVRMSHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DVRMSHelper.type ();
  }

}
