package com.dvrms.replica2;
/**
* DVRMS/DVRMSOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DVRMS.idl
* vendredi 27 f�vrier 2026 18 h 00 EST
*/

public interface DVRMSOperations 
{

  // ================= MANAGER OPERATIONS =================
  String addVehicle (String managerID, String vehicleNumber, String vehicleType, String vehicleID, double price);
  String removeVehicle (String managerID, String vehicleID);
  String listAvailableVehicle (String managerID);

  // ================= CUSTOMER OPERATIONS =================
  String reserveVehicle (String customerID, String vehicleID, String startDate, String endDate);
  String cancelReservation (String customerID, String vehicleID);
  String updateReservation (String customerID, String vehicleID, String newStartDate, String newEndDate);
  String findVehicle (String customerID, String vehicleType);
  String displayCurrentBudget (String customerID);
  String displayReservations (String customerID);
  String displayReservationsLocal (String customerID);
  String retryCustomerWaitlistsLocal (String customerID);
} // interface DVRMSOperations
