package FrontEndApp;


/**
* FrontEndApp/FrontEnd.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEndApp.idl
* Friday, April 10, 2026 3:33:11 o'clock PM EDT
*/


// --------------------
public interface FrontEnd extends FrontEndOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FrontEnd
