package FrontEndApp;


/**
* FrontEndApp/FrontEndOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEndApp.idl
* Friday, April 10, 2026 3:33:11 o'clock PM EDT
*/


// --------------------
public interface FrontEndOperations 
{

  // ----- Manager Operations -----
  String addVehicle (String managerID, String vehicleNumber, String vehicleType, String vehicleID, double price);
  String removeVehicle (String managerID, String vehicleID);
  String listAvailableVehicles (String managerID);

  // ----- Customer Operations -----
  String reserveVehicle (String customerID, String vehicleID, String startDate, String endDate);
  String remoteReserveVehicle (String customerID, String vehicleID, String startDate, String endDate, double budgetAmount);
  String cancelReservation (String customerID, String vehicleID);
  String remoteCancelReservation (String customerID, String vehicleID, double budgetAmount);
  String updateReservation (String customerID, String vehicleID, String newStartDate, String newEndDate);
  String findVehicle (String customerID, String vehicleType);
  String addToWaitingList (String customerID, String vehicleID, String startDate, String endDate);
  String getLocalVehiclesByType (String vehicleType);
} // interface FrontEndOperations
