package FrontEndApp;

/**
* FrontEndApp/ReservationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEndApp.idl
* Friday, April 10, 2026 3:33:11 o'clock PM EDT
*/

public final class ReservationHolder implements org.omg.CORBA.portable.Streamable
{
  public FrontEndApp.Reservation value = null;

  public ReservationHolder ()
  {
  }

  public ReservationHolder (FrontEndApp.Reservation initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FrontEndApp.ReservationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FrontEndApp.ReservationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FrontEndApp.ReservationHelper.type ();
  }

}
