package FrontEndApp;


/**
* FrontEndApp/Reservation.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEndApp.idl
* Friday, April 10, 2026 3:33:11 o'clock PM EDT
*/

public final class Reservation implements org.omg.CORBA.portable.IDLEntity
{
  public String customerID = null;
  public String vehicleID = null;
  public String startDate = null;

  // format: ddmmyyyy
  public String endDate = null;

  public Reservation ()
  {
  } // ctor

  public Reservation (String _customerID, String _vehicleID, String _startDate, String _endDate)
  {
    customerID = _customerID;
    vehicleID = _vehicleID;
    startDate = _startDate;
    endDate = _endDate;
  } // ctor

} // class Reservation
