package FrontEndApp;


/**
* FrontEndApp/Vehicle.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEndApp.idl
* Friday, April 10, 2026 3:33:11 o'clock PM EDT
*/

public final class Vehicle implements org.omg.CORBA.portable.IDLEntity
{
  public String vehicleID = null;
  public String vehicleNumber = null;

  // license plate or internal number
  public String vehicleType = null;

  // e.g., Sedan, SUV, Truck
  public double price = (double)0;

  public Vehicle ()
  {
  } // ctor

  public Vehicle (String _vehicleID, String _vehicleNumber, String _vehicleType, double _price)
  {
    vehicleID = _vehicleID;
    vehicleNumber = _vehicleNumber;
    vehicleType = _vehicleType;
    price = _price;
  } // ctor

} // class Vehicle
