package FrontEndApp;

/**
* FrontEndApp/VehicleHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEndApp.idl
* Friday, April 10, 2026 3:33:11 o'clock PM EDT
*/

public final class VehicleHolder implements org.omg.CORBA.portable.Streamable
{
  public FrontEndApp.Vehicle value = null;

  public VehicleHolder ()
  {
  }

  public VehicleHolder (FrontEndApp.Vehicle initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FrontEndApp.VehicleHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FrontEndApp.VehicleHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FrontEndApp.VehicleHelper.type ();
  }

}
