package FrontEndApp;


/**
* FrontEndApp/WaitingRequest.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEndApp.idl
* Friday, April 10, 2026 3:33:11 o'clock PM EDT
*/

public final class WaitingRequest implements org.omg.CORBA.portable.IDLEntity
{
  public String customerID = null;
  public String startDate = null;

  // format: ddmmyyyy
  public String endDate = null;

  public WaitingRequest ()
  {
  } // ctor

  public WaitingRequest (String _customerID, String _startDate, String _endDate)
  {
    customerID = _customerID;
    startDate = _startDate;
    endDate = _endDate;
  } // ctor

} // class WaitingRequest
