package FrontEndApp;

/**
* FrontEndApp/WaitingRequestHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from FrontEndApp.idl
* Friday, April 10, 2026 3:33:11 o'clock PM EDT
*/

public final class WaitingRequestHolder implements org.omg.CORBA.portable.Streamable
{
  public FrontEndApp.WaitingRequest value = null;

  public WaitingRequestHolder ()
  {
  }

  public WaitingRequestHolder (FrontEndApp.WaitingRequest initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FrontEndApp.WaitingRequestHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FrontEndApp.WaitingRequestHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FrontEndApp.WaitingRequestHelper.type ();
  }

}
