package DVRMS;


/**
* DVRMS/DVRMSOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DVRMS.idl
* vendredi 13 mars 2026 21 h 55 EDT
*/

public interface DVRMSOperations 
{

  // ================= MANAGER OPERATIONS =================
  String addVehicle (String managerID, String vehicleNumber, String vehicleType, String vehicleID, double price);
  String removeVehicle (String managerID, String vehicleID);
  String listAvailableVehicle (String managerID);

  // ================= CUSTOMER OPERATIONS =================
  String reserveVehicle (String customerID, String vehicleID, String startDate, String endDate);
  String updateReservation (String customerID, String vehicleID, String newStartDate, String newEndDate);
  String sendAtomicUpdate (String vID, String cID, String start, String end);
  String cancelReservation (String customerID, String vehicleID);
  String findVehicle (String customerID, String vehicleType);
  String findLocalVehicle (String vtype);
} // interface DVRMSOperations
