package DVRMS;


/**
* DVRMS/DVRMS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DVRMS.idl
* vendredi 13 mars 2026 21 h 55 EDT
*/

public interface DVRMS extends DVRMSOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DVRMS
