package com.dvrms.replica5.RentalOfficeApp;


/**
* RentalOfficeApp/_RentalOfficeStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RentalOfficeApp.idl
* Sunday, April 12, 2026 12:22:14 o'clock AM EDT
*/


// --------------------
public class _RentalOfficeStub extends org.omg.CORBA.portable.ObjectImpl implements RentalOfficeApp.RentalOffice
{


  // ----- Manager Operations -----
  public String addVehicle (String managerID, String vehicleNumber, String vehicleType, String vehicleID, double price)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("addVehicle", true);
                $out.write_string (managerID);
                $out.write_string (vehicleNumber);
                $out.write_string (vehicleType);
                $out.write_string (vehicleID);
                $out.write_double (price);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return addVehicle (managerID, vehicleNumber, vehicleType, vehicleID, price        );
            } finally {
                _releaseReply ($in);
            }
  } // addVehicle

  public String removeVehicle (String managerID, String vehicleID)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("removeVehicle", true);
                $out.write_string (managerID);
                $out.write_string (vehicleID);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return removeVehicle (managerID, vehicleID        );
            } finally {
                _releaseReply ($in);
            }
  } // removeVehicle

  public String listAvailableVehicles (String managerID)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listAvailableVehicles", true);
                $out.write_string (managerID);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listAvailableVehicles (managerID        );
            } finally {
                _releaseReply ($in);
            }
  } // listAvailableVehicles


  // ----- Customer Operations -----
  public String reserveVehicle (String customerID, String vehicleID, String startDate, String endDate)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("reserveVehicle", true);
                $out.write_string (customerID);
                $out.write_string (vehicleID);
                $out.write_string (startDate);
                $out.write_string (endDate);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return reserveVehicle (customerID, vehicleID, startDate, endDate        );
            } finally {
                _releaseReply ($in);
            }
  } // reserveVehicle

  public String remoteReserveVehicle (String customerID, String vehicleID, String startDate, String endDate, double budgetAmount)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("remoteReserveVehicle", true);
                $out.write_string (customerID);
                $out.write_string (vehicleID);
                $out.write_string (startDate);
                $out.write_string (endDate);
                $out.write_double (budgetAmount);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return remoteReserveVehicle (customerID, vehicleID, startDate, endDate, budgetAmount        );
            } finally {
                _releaseReply ($in);
            }
  } // remoteReserveVehicle

  public String cancelReservation (String customerID, String vehicleID)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("cancelReservation", true);
                $out.write_string (customerID);
                $out.write_string (vehicleID);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return cancelReservation (customerID, vehicleID        );
            } finally {
                _releaseReply ($in);
            }
  } // cancelReservation

  public String remoteCancelReservation (String customerID, String vehicleID, double budgetAmount)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("remoteCancelReservation", true);
                $out.write_string (customerID);
                $out.write_string (vehicleID);
                $out.write_double (budgetAmount);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return remoteCancelReservation (customerID, vehicleID, budgetAmount        );
            } finally {
                _releaseReply ($in);
            }
  } // remoteCancelReservation

  public String updateReservation (String customerID, String vehicleID, String newStartDate, String newEndDate)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("updateReservation", true);
                $out.write_string (customerID);
                $out.write_string (vehicleID);
                $out.write_string (newStartDate);
                $out.write_string (newEndDate);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return updateReservation (customerID, vehicleID, newStartDate, newEndDate        );
            } finally {
                _releaseReply ($in);
            }
  } // updateReservation

  public String findVehicle (String customerID, String vehicleType)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("findVehicle", true);
                $out.write_string (customerID);
                $out.write_string (vehicleType);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return findVehicle (customerID, vehicleType        );
            } finally {
                _releaseReply ($in);
            }
  } // findVehicle

  public String addToWaitingList (String customerID, String vehicleID, String startDate, String endDate)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("addToWaitingList", true);
                $out.write_string (customerID);
                $out.write_string (vehicleID);
                $out.write_string (startDate);
                $out.write_string (endDate);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return addToWaitingList (customerID, vehicleID, startDate, endDate        );
            } finally {
                _releaseReply ($in);
            }
  } // addToWaitingList

  public String getLocalVehiclesByType (String vehicleType)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("getLocalVehiclesByType", true);
                $out.write_string (vehicleType);
                $in = _invoke ($out);
                String $result = $in.read_string ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return getLocalVehiclesByType (vehicleType        );
            } finally {
                _releaseReply ($in);
            }
  } // getLocalVehiclesByType

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:RentalOfficeApp/RentalOffice:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _RentalOfficeStub
