package package com.dvrms.replica5.RentalOfficeApp;


/**
* RentalOfficeApp/CustomerBudget.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RentalOfficeApp.idl
* Monday, February 23, 2026 4:24:04 o'clock PM EST
*/

public final class CustomerBudget implements org.omg.CORBA.portable.IDLEntity
{
  public String customerID = null;
  public double budgetAmount = (double)0;

  public CustomerBudget ()
  {
  } // ctor

  public CustomerBudget (String _customerID, double _budgetAmount)
  {
    customerID = _customerID;
    budgetAmount = _budgetAmount;
  } // ctor

} // class CustomerBudget
