package com.dvrms.replica5.RentalOfficeApp;

/**
* RentalOfficeApp/CustomerBudgetHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RentalOfficeApp.idl
* Monday, February 23, 2026 4:24:04 o'clock PM EST
*/

public final class CustomerBudgetHolder implements org.omg.CORBA.portable.Streamable
{
  public RentalOfficeApp.CustomerBudget value = null;

  public CustomerBudgetHolder ()
  {
  }

  public CustomerBudgetHolder (RentalOfficeApp.CustomerBudget initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RentalOfficeApp.CustomerBudgetHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RentalOfficeApp.CustomerBudgetHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RentalOfficeApp.CustomerBudgetHelper.type ();
  }

}
