package RentalOfficeApp;


/**
* RentalOfficeApp/RentalOfficeOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RentalOfficeApp.idl
* Sunday, April 12, 2026 12:22:14 o'clock AM EDT
*/


// --------------------
public interface RentalOfficeOperations 
{

  // ----- Manager Operations -----
  String addVehicle (String managerID, String vehicleNumber, String vehicleType, String vehicleID, double price);
  String removeVehicle (String managerID, String vehicleID);
  String listAvailableVehicles (String managerID);

  // ----- Customer Operations -----
  String reserveVehicle (String customerID, String vehicleID, String startDate, String endDate);
  String remoteReserveVehicle (String customerID, String vehicleID, String startDate, String endDate, double budgetAmount);
  String cancelReservation (String customerID, String vehicleID);
  String remoteCancelReservation (String customerID, String vehicleID, double budgetAmount);
  String updateReservation (String customerID, String vehicleID, String newStartDate, String newEndDate);
  String findVehicle (String customerID, String vehicleType);
  String addToWaitingList (String customerID, String vehicleID, String startDate, String endDate);
  String getLocalVehiclesByType (String vehicleType);
} // interface RentalOfficeOperations
