package com.dvrms.replica5.RentalOfficeApp;


/**
* RentalOfficeApp/RentalOfficeHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RentalOfficeApp.idl
* Sunday, April 12, 2026 12:22:14 o'clock AM EDT
*/


// --------------------
abstract public class RentalOfficeHelper
{
  private static String  _id = "IDL:RentalOfficeApp/RentalOffice:1.0";

  public static void insert (org.omg.CORBA.Any a, RentalOfficeApp.RentalOffice that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static RentalOfficeApp.RentalOffice extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (RentalOfficeApp.RentalOfficeHelper.id (), "RentalOffice");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static RentalOfficeApp.RentalOffice read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_RentalOfficeStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, RentalOfficeApp.RentalOffice value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static RentalOfficeApp.RentalOffice narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof RentalOfficeApp.RentalOffice)
      return (RentalOfficeApp.RentalOffice)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      RentalOfficeApp._RentalOfficeStub stub = new RentalOfficeApp._RentalOfficeStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static RentalOfficeApp.RentalOffice unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof RentalOfficeApp.RentalOffice)
      return (RentalOfficeApp.RentalOffice)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      RentalOfficeApp._RentalOfficeStub stub = new RentalOfficeApp._RentalOfficeStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
