package RentalOfficeApp;

/**
* RentalOfficeApp/RentalOfficeHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RentalOfficeApp.idl
* Sunday, April 12, 2026 12:22:14 o'clock AM EDT
*/


// --------------------
public final class RentalOfficeHolder implements org.omg.CORBA.portable.Streamable
{
  public RentalOfficeApp.RentalOffice value = null;

  public RentalOfficeHolder ()
  {
  }

  public RentalOfficeHolder (RentalOfficeApp.RentalOffice initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RentalOfficeApp.RentalOfficeHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RentalOfficeApp.RentalOfficeHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RentalOfficeApp.RentalOfficeHelper.type ();
  }

}
