package RentalOfficeApp;


/**
* RentalOfficeApp/RentalOfficePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RentalOfficeApp.idl
* Sunday, April 12, 2026 12:22:14 o'clock AM EDT
*/


// --------------------
public abstract class RentalOfficePOA extends org.omg.PortableServer.Servant
 implements RentalOfficeApp.RentalOfficeOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("addVehicle", new java.lang.Integer (0));
    _methods.put ("removeVehicle", new java.lang.Integer (1));
    _methods.put ("listAvailableVehicles", new java.lang.Integer (2));
    _methods.put ("reserveVehicle", new java.lang.Integer (3));
    _methods.put ("remoteReserveVehicle", new java.lang.Integer (4));
    _methods.put ("cancelReservation", new java.lang.Integer (5));
    _methods.put ("remoteCancelReservation", new java.lang.Integer (6));
    _methods.put ("updateReservation", new java.lang.Integer (7));
    _methods.put ("findVehicle", new java.lang.Integer (8));
    _methods.put ("addToWaitingList", new java.lang.Integer (9));
    _methods.put ("getLocalVehiclesByType", new java.lang.Integer (10));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {

  // ----- Manager Operations -----
       case 0:  // RentalOfficeApp/RentalOffice/addVehicle
       {
         String managerID = in.read_string ();
         String vehicleNumber = in.read_string ();
         String vehicleType = in.read_string ();
         String vehicleID = in.read_string ();
         double price = in.read_double ();
         String $result = null;
         $result = this.addVehicle (managerID, vehicleNumber, vehicleType, vehicleID, price);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 1:  // RentalOfficeApp/RentalOffice/removeVehicle
       {
         String managerID = in.read_string ();
         String vehicleID = in.read_string ();
         String $result = null;
         $result = this.removeVehicle (managerID, vehicleID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 2:  // RentalOfficeApp/RentalOffice/listAvailableVehicles
       {
         String managerID = in.read_string ();
         String $result = null;
         $result = this.listAvailableVehicles (managerID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }


  // ----- Customer Operations -----
       case 3:  // RentalOfficeApp/RentalOffice/reserveVehicle
       {
         String customerID = in.read_string ();
         String vehicleID = in.read_string ();
         String startDate = in.read_string ();
         String endDate = in.read_string ();
         String $result = null;
         $result = this.reserveVehicle (customerID, vehicleID, startDate, endDate);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 4:  // RentalOfficeApp/RentalOffice/remoteReserveVehicle
       {
         String customerID = in.read_string ();
         String vehicleID = in.read_string ();
         String startDate = in.read_string ();
         String endDate = in.read_string ();
         double budgetAmount = in.read_double ();
         String $result = null;
         $result = this.remoteReserveVehicle (customerID, vehicleID, startDate, endDate, budgetAmount);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // RentalOfficeApp/RentalOffice/cancelReservation
       {
         String customerID = in.read_string ();
         String vehicleID = in.read_string ();
         String $result = null;
         $result = this.cancelReservation (customerID, vehicleID);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // RentalOfficeApp/RentalOffice/remoteCancelReservation
       {
         String customerID = in.read_string ();
         String vehicleID = in.read_string ();
         double budgetAmount = in.read_double ();
         String $result = null;
         $result = this.remoteCancelReservation (customerID, vehicleID, budgetAmount);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 7:  // RentalOfficeApp/RentalOffice/updateReservation
       {
         String customerID = in.read_string ();
         String vehicleID = in.read_string ();
         String newStartDate = in.read_string ();
         String newEndDate = in.read_string ();
         String $result = null;
         $result = this.updateReservation (customerID, vehicleID, newStartDate, newEndDate);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 8:  // RentalOfficeApp/RentalOffice/findVehicle
       {
         String customerID = in.read_string ();
         String vehicleType = in.read_string ();
         String $result = null;
         $result = this.findVehicle (customerID, vehicleType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 9:  // RentalOfficeApp/RentalOffice/addToWaitingList
       {
         String customerID = in.read_string ();
         String vehicleID = in.read_string ();
         String startDate = in.read_string ();
         String endDate = in.read_string ();
         String $result = null;
         $result = this.addToWaitingList (customerID, vehicleID, startDate, endDate);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 10:  // RentalOfficeApp/RentalOffice/getLocalVehiclesByType
       {
         String vehicleType = in.read_string ();
         String $result = null;
         $result = this.getLocalVehiclesByType (vehicleType);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:RentalOfficeApp/RentalOffice:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public RentalOffice _this() 
  {
    return RentalOfficeHelper.narrow(
    super._this_object());
  }

  public RentalOffice _this(org.omg.CORBA.ORB orb) 
  {
    return RentalOfficeHelper.narrow(
    super._this_object(orb));
  }


} // class RentalOfficePOA
