package RentalOfficeApp;

/**
* RentalOfficeApp/ReservationHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RentalOfficeApp.idl
* Sunday, April 12, 2026 12:22:14 o'clock AM EDT
*/

public final class ReservationHolder implements org.omg.CORBA.portable.Streamable
{
  public RentalOfficeApp.Reservation value = null;

  public ReservationHolder ()
  {
  }

  public ReservationHolder (RentalOfficeApp.Reservation initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RentalOfficeApp.ReservationHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RentalOfficeApp.ReservationHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RentalOfficeApp.ReservationHelper.type ();
  }

}
