package RentalOfficeApp;


/**
* RentalOfficeApp/Reservation.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RentalOfficeApp.idl
* Sunday, April 12, 2026 12:22:14 o'clock AM EDT
*/

public final class Reservation implements org.omg.CORBA.portable.IDLEntity
{
  public String customerID = null;
  public String vehicleID = null;
  public String startDate = null;

  // format: ddmmyyyy
  public String endDate = null;

  public Reservation ()
  {
  } // ctor

  public Reservation (String _customerID, String _vehicleID, String _startDate, String _endDate)
  {
    customerID = _customerID;
    vehicleID = _vehicleID;
    startDate = _startDate;
    endDate = _endDate;
  } // ctor

} // class Reservation
