package com.dvrms.replica5.RentalOfficeApp;


/**
* RentalOfficeApp/Vehicle.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RentalOfficeApp.idl
* Sunday, April 12, 2026 12:22:14 o'clock AM EDT
*/

public final class Vehicle implements org.omg.CORBA.portable.IDLEntity
{
  public String vehicleID = null;
  public String vehicleNumber = null;

  // license plate or internal number
  public String vehicleType = null;

  // e.g., Sedan, SUV, Truck
  public double price = (double)0;

  public Vehicle ()
  {
  } // ctor

  public Vehicle (String _vehicleID, String _vehicleNumber, String _vehicleType, double _price)
  {
    vehicleID = _vehicleID;
    vehicleNumber = _vehicleNumber;
    vehicleType = _vehicleType;
    price = _price;
  } // ctor

} // class Vehicle
