package com.dvrms.replica5.RentalOfficeApp;


/**
* RentalOfficeApp/WaitingRequest.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RentalOfficeApp.idl
* Sunday, April 12, 2026 12:22:14 o'clock AM EDT
*/

public final class WaitingRequest implements org.omg.CORBA.portable.IDLEntity
{
  public String customerID = null;
  public String startDate = null;

  // format: ddmmyyyy
  public String endDate = null;

  public WaitingRequest ()
  {
  } // ctor

  public WaitingRequest (String _customerID, String _startDate, String _endDate)
  {
    customerID = _customerID;
    startDate = _startDate;
    endDate = _endDate;
  } // ctor

} // class WaitingRequest
