package com.dvrms.replica5.RentalOfficeApp;

/**
* RentalOfficeApp/WaitingRequestHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RentalOfficeApp.idl
* Sunday, April 12, 2026 12:22:14 o'clock AM EDT
*/

public final class WaitingRequestHolder implements org.omg.CORBA.portable.Streamable
{
  public RentalOfficeApp.WaitingRequest value = null;

  public WaitingRequestHolder ()
  {
  }

  public WaitingRequestHolder (RentalOfficeApp.WaitingRequest initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RentalOfficeApp.WaitingRequestHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RentalOfficeApp.WaitingRequestHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RentalOfficeApp.WaitingRequestHelper.type ();
  }

}
