package com.dvrms.replica1.RentalOfficeApp;


/**
* RentalOfficeApp/RentalOffice.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RentalOfficeApp.idl
* Sunday, April 12, 2026 12:22:14 o'clock AM EDT
*/


// --------------------
public interface RentalOffice extends RentalOfficeOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface RentalOffice
