package com.dvrms.replica1.RentalOfficeApp;


/**
* RentalOfficeApp/VehicleHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RentalOfficeApp.idl
* Sunday, April 12, 2026 12:22:14 o'clock AM EDT
*/

abstract public class VehicleHelper
{
  private static String  _id = "IDL:RentalOfficeApp/Vehicle:1.0";

  public static void insert (org.omg.CORBA.Any a, RentalOfficeApp.Vehicle that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static RentalOfficeApp.Vehicle extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  private static boolean __active = false;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      synchronized (org.omg.CORBA.TypeCode.class)
      {
        if (__typeCode == null)
        {
          if (__active)
          {
            return org.omg.CORBA.ORB.init().create_recursive_tc ( _id );
          }
          __active = true;
          org.omg.CORBA.StructMember[] _members0 = new org.omg.CORBA.StructMember [4];
          org.omg.CORBA.TypeCode _tcOf_members0 = null;
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[0] = new org.omg.CORBA.StructMember (
            "vehicleID",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[1] = new org.omg.CORBA.StructMember (
            "vehicleNumber",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().create_string_tc (0);
          _members0[2] = new org.omg.CORBA.StructMember (
            "vehicleType",
            _tcOf_members0,
            null);
          _tcOf_members0 = org.omg.CORBA.ORB.init ().get_primitive_tc (org.omg.CORBA.TCKind.tk_double);
          _members0[3] = new org.omg.CORBA.StructMember (
            "price",
            _tcOf_members0,
            null);
          __typeCode = org.omg.CORBA.ORB.init ().create_struct_tc (RentalOfficeApp.VehicleHelper.id (), "Vehicle", _members0);
          __active = false;
        }
      }
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static RentalOfficeApp.Vehicle read (org.omg.CORBA.portable.InputStream istream)
  {
    RentalOfficeApp.Vehicle value = new RentalOfficeApp.Vehicle ();
    value.vehicleID = istream.read_string ();
    value.vehicleNumber = istream.read_string ();
    value.vehicleType = istream.read_string ();
    value.price = istream.read_double ();
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, RentalOfficeApp.Vehicle value)
  {
    ostream.write_string (value.vehicleID);
    ostream.write_string (value.vehicleNumber);
    ostream.write_string (value.vehicleType);
    ostream.write_double (value.price);
  }

}
