package com.dvrms.replica1.RentalOfficeApp;

/**
* RentalOfficeApp/VehicleHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from RentalOfficeApp.idl
* Sunday, April 12, 2026 12:22:14 o'clock AM EDT
*/

public final class VehicleHolder implements org.omg.CORBA.portable.Streamable
{
  public Vehicle value = null;

  public VehicleHolder ()
  {
  }

  public VehicleHolder (Vehicle initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = VehicleHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    VehicleHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return VehicleHelper.type ();
  }

}
